#
# Generic 128x128 ST7735
#
target_compile_definitions(firmware PRIVATE
    MIPI_DISPLAY_PIN_DC=20
    MIPI_DISPLAY_PIN_CS=17
    MIPI_DISPLAY_PIN_CLK=18
    MIPI_DISPLAY_PIN_MOSI=19
    MIPI_DISPLAY_PIN_RST=21
    MIPI_DISPLAY_PIN_BL=-1
    MIPI_DISPLAY_PIN_MISO=-1

    MIPI_DISPLAY_SPI_PORT=spi0
    MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ=62500000
    MIPI_DISPLAY_PIXEL_FORMAT=MIPI_DCS_PIXEL_FORMAT_16BIT

    MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_BGR|MIPI_DCS_ADDRESS_MODE_MIRROR_Y|MIPI_DCS_ADDRESS_MODE_MIRROR_X
    MIPI_DISPLAY_WIDTH=128
    MIPI_DISPLAY_HEIGHT=128
    MIPI_DISPLAY_OFFSET_X=2
    MIPI_DISPLAY_OFFSET_Y=1

    # MIPI_DISPLAY_ADDRESS_MODE=MIPI_DCS_ADDRESS_MODE_BGR|MIPI_DCS_ADDRESS_MODE_SWAP_XY|MIPI_DCS_ADDRESS_MODE_MIRROR_Y
    # MIPI_DISPLAY_WIDTH=128
    # MIPI_DISPLAY_HEIGHT=128
    # MIPI_DISPLAY_OFFSET_X=2
    # MIPI_DISPLAY_OFFSET_Y=2

    MIPI_DISPLAY_INVERT=1
)